Reading Data From Different Sources

In [3]:
import pandas as pd
from io import StringIO

Data = '[{"employee_name": "James", "employee_id": 1, "employee_salary": 50000, "employee_age": 30, "profile_image": ""}]'
df = pd.read_json(StringIO(Data))

print(df)

  employee_name  employee_id  employee_salary  employee_age profile_image
0         James            1            50000            30

In [2]:
# Convert DataFrame to JSON format with 'records' orientation
df.to_json(orient='records')

'[{"employee_name":"James","employee_id":1,"employee_salary":50000,"employee_age":30,"profile_image":""}]'

In [3]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","employee_id":1,"employee_salary":50000,"employee_age":30,"profile_image":""}}'

In [4]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header=None)
df.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [5]:
#convert into .csv file
df.to_csv("wine.csv")

In [9]:
df = pd.read_html("https://statisticstimes.com/sports/ipl/all-ipl-points-table.php",header=0)
df

[Empty DataFrame
 Columns: [Source, www.iplt20.com]
 Index: [],
    No               Team   M  W   L  N/R  Net RR         For     Against  Pts  \
 0   1    Q PBKS (Punjab)  14  9   4    1   0.372  2447/246.4  2395/250.5   19
 1   2  Q RCB (Bangalore)  14  9   4    1   0.301  2357/243.5  2321/247.5   19
 2   3     Q GT (Gujarat)  14  9   5    0   0.254  2684/271.5  2639/274.2   18
 3   4      Q MI (Mumbai)  14  8   6    0   1.142  2472/261.2  2301/276.4   16
 4   5       E DC (Delhi)  14  7   6    1   0.011  2354/250.4  2409/256.5   15
 5   6  E SRH (Hyderabad)  14  6   7    1  -0.241  2519/255.3  2451/242.4   13
 6   7    E LSG (Lucknow)  14  6   8    0  -0.376  2732/275.4  2779/270.1   12
 7   8    E KKR (Kolkata)  14  5   7    2  -0.305  1995/227.4  2075/228.5   12
 8   9   E RR (Rajasthan)  14  4  10    0  -0.549  2603/273.0  2773/275.0    8
 9  10    E CSK (Chennai)  14  4  10    0  -0.647  2441/278.2  2461/261.2    8

   Form (1......14)
 0   WWLWLWWLNWWWLW
 1   WWLWLWLWWWWNLW
 2   LWWWWLWWLWWWLL
 3   LLWLLWWWWWWLWL
 4   WWWWLWLWLLNLLW
 5   WLLLLWLLWLNWWW
 6   LWLWWWLWLLLLWL
 7   LWLWLWLLNWWLNL
 8   LLWWLLLLLWLLLW
 9   WLLLLLWLLLLWLW  ,
     Rank  Team 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019  \
 0      1   CSK    3    2    3    2    4    1    3    1    -    -    2    2
 1      2    MI    5    7    1    3    3    2    4    2    5    1    5    1
 2      3   SRH    -    -    -    -    -    4    6    6    3    3    1    4
 3      4    GL    -    -    -    -    -    -    -    -    1    7    -    -
 4      5   RPS    -    -    -    -    -    -    -    -    7    2    -    -
 5      6   KKR    6    8    6    4    2    7    2    5    4    4    3    5
 6      7   RCB    7    3    4    1    5    5    7    3    2    8    6    8
 7      8    RR    1    6    7    6    7    3    5    4    -    -    4    7
 8      9    DD    4    1    5   10    1    9    8    7    6    6    8    3
 9     10  KXIP    2    5    8    5    6    6    1    8    8    5    7    6
 10    11    DC    8    4    2    7    8    -    -    -    -    -    -    -
 11    12   KTK    -    -    -    8    -    -    -    -    -    -    -    -
 12    13   PWI    -    -    -    9    9    8    -    -    -    -    -    -

    2020    AVG
 0     7  2.727
 1     1  3.077
 2     3  3.750
 3     -  4.000
 4     -  4.500
 5     5  4.692
 6     4  4.846
 7     8  5.273
 8     2  5.385
 9     6  5.615
 10    -  5.800
 11    -  8.000
 12    -  8.667  ,
     Rank  Team  Match  Won  Lost  N/R  Net RR           For       Against  \
 0      1    MI    186  108    77    1   0.365  29474/3593.2  28366/3619.3
 1      2   KKR    186   93    89    4   0.063  27743/3440.5  27589/3448.3
 2      3   CSK    158   93    63    2   0.284  24679/3023.1  23710/3009.2
 3      4   RCB    186   86    94    6  -0.078  28104/3436.4    28499/3452
 4      6    DC    186   84    99    3  -0.163  27777/3480.1  28358/3481.4
 5      5  PBKS    186   87    99    0  -0.183  29204/3574.3  29641/3548.2
 6      7    RR    158   78    75    5  -0.121  23474/2946.4  23697/2930.1
 7      8   SRH     86   48    37    1   0.085  12897/1613.1  12857/1625.3
 8      9   DCH     72   27    44    1  -0.170  10980/1398.2  11100/1383.4
 9     10   RPS     28   14    14    0   0.103    4205/515.5    4156/516.2
 10    11    GL     28   13    15    0  -0.462    4536/539.2    4757/536.1
 11    12   PWI     46   12    33    1  -0.591    6358/885.3    6801/875.1
 12    13   KTK     14    6     8    0  -0.214    1901/256.2    1989/260.4

     Points
 0      217
 1      190
 2      188
 3      178
 4      171
 5      174
 6      161
 7       97
 8       55
 9       28
 10      26
 11      25
 12      12  ,
    Rank             Team  Match  Won  Lost  N/R  Net RR         For  \
 0     1    KKR (Kolkata)     14    9     3    2   1.428  2389/225.0
 1     2  SRH (Hyderabad)     14    8     5    1   0.414  2605/247.0
 2     3   RR (Rajasthan)     14    8     5    1   0.273  2334/252.1
 3     4  RCB (Bangalore)     14    7     7    0   0.459  2758/269.0
 4     5    CSK (Chennai)     14    7     7    0   0.392  2524/274.4
 5     6       DC (Delhi)     14    7     7    0  -0.377  2573/267.0
 6     7    LSG (Lucknow)     14    7     7    0  -0.667  2483/277.5
 7     8     GT (Gujarat)     14    5     7    2  -1.063  2040/238.2
 8     9    PBKS (Punjab)     14    5     9    0  -0.353  2487/274.3
 9    10      MI (Mumbai)     14    4    10    0  -0.318  2568/268.5

       Against  Points
 0  2135/232.2      20
 1  2599/256.3      17
 2  2310/257.1      17
 3  2646/270.1      14
 4  2415/274.3      14
 5  2762/275.5      14
 6  2521/262.3      14
 7  2101/218.2      12
 8  2612/277.3      10
 9  2660/269.3       8  ,
    Rank             Team  Match  Won  Lost  N/R  Net RR         For  \
 0     1     GT (Gujarat)     14   10     4    0   0.809  2450/268.1
 1     2    CSK (Chennai)     14    8     5    1   0.652  2369/254.3
 2     3    LSG (Lucknow)     14    8     5    1   0.284  2253/255.2
 3     4      MI (Mumbai)     14    8     6    0  -0.044  2592/270.3
 4     5   RR (Rajasthan)     14    7     7    0   0.148  2419/272.1
 5     6  RCB (Bangalore)     14    7     7    0   0.135  2502/275.4
 6     7    KKR (Kolkata)     14    6     8    0  -0.239  2463/274.3
 7     8    PBKS (Punjab)     14    6     8    0  -0.304  2518/275.3
 8     9       DC (Delhi)     14    5     9    0  -0.808  2182/276.0
 9    10  SRH (Hyderabad)     14    4    10    0  -0.590  2376/277.1

       Against  Points
 0  2326/279.2      20
 1  2232/257.5      17
 2  2216/259.3      17
 3  2620/272.1      16
 4  2389/273.2      14
 5  2435/272.2      14
 6  2432/264.0      12
 7  2564/271.3      12
 8  2424/278.1      10
 9  2486/271.2       8  ,
    Rank             Team  Match  Won  Lost  N/R  Net RR         For  \
 0     1     GT (Gujarat)     14   10     4    0   0.316  2339/278.1
 1     2   RR (Rajasthan)     14    9     5    0   0.298  2464/279.2
 2     3    LSG (Lucknow)     14    9     5    0   0.251  2355/279.1
 3     4  RCB (Bangalore)     14    8     6    0  -0.253  2268/275.4
 4     5       DC (Delhi)     14    7     7    0   0.204  2341/266.0
 5     6    PBKS (Punjab)     14    7     7    0   0.126  2343/270.1
 6     7    KKR (Kolkata)     14    6     8    0   0.146  2223/268.1
 7     8  SRH (Hyderabad)     14    6     8    0  -0.379  2197/261.3
 8     9    CSK (Chennai)     14    4    10    0  -0.203  2288/280.0
 9    10      MI (Mumbai)     14    4    10    0  -0.506  2217/273.2

       Against  Points
 0  2216/273.5      20
 1  2351/275.5      18
 2  2289/279.4      18
 3  2260/266.3      16
 4  2397/278.5      14
 5  2252/263.3      14
 6  2249/276.1      12
 7  2416/275.1      12
 8  2254/269.1       8
 9  2351/272.5       8  ,
    Rank             Team  Match  Won  Lost  N/R  Net RR         For  \
 0     1       DC (Delhi)     14   10     4    0   0.481  2180/267.0
 1     2    CSK (Chennai)     14    9     5    0   0.455  2368/272.0
 2     3  RCB (Bangalore)     14    9     5    0  -0.140  2165/273.4
 3     4    KKR (Kolkata)     14    7     7    0   0.587  2119/259.5
 4     5      MI (Mumbai)     14    7     7    0   0.116  2117/265.5
 5     6    PBKS (Punjab)     14    6     8    0  -0.001  2150/270.1
 6     7   RR (Rajasthan)     14    5     9    0  -0.993  2196/276.0
 7     8  SRH (Hyderabad)     14    3    11    0  -0.545  2077/277.1

       Against  Points
 0  2136/278.0      20
 1  2218/268.5      18
 2  2159/268.1      18
 3  2080/274.5      14
 4  2128/271.1      14
 5  2117/266.0      12
 6  2318/259.0      10
 7  2216/275.4       6  ,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    MI     14    9     5    0   1.107  2378/262.2  2187/274.5      18
 1     2    DC     14    8     6    0  -0.109  2289/278.5  2271/273.0      16
 2     3   SRH     14    7     7    0   0.608  2225/269.3  2125/277.5      14
 3     4   RCB     14    7     7    0  -0.172  2147/272.2  2183/271.0      14
 4     5   KKR     14    7     7    0  -0.214  2219/278.0  2206/269.1      14
 5     6  PBKS     14    6     8    0  -0.162  2335/277.5  2343/273.3      12
 6     7   CSK     14    6     8    0  -0.455  2191/274.3  2275/269.4      12
 7     8    RR     14    6     8    0  -0.569  2288/272.4  2482/277.0      12,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    MI     14    9     5    0   0.421  2380/275.1  2282/277.2      18
 1     2   CSK     14    9     5    0   0.131  2043/274.1  2012/274.5      18
 2     3    DC     14    9     5    0   0.044  2207/272.5  2238/278.1      18
 3     4   SRH     14    6     8    0   0.577  2288/269.2  2200/277.5      12
 4     5   KKR     14    6     8    0   0.028  2466/270.4  2419/266.2      12
 5     6  PBKS     14    6     8    0  -0.251  2429/276.3  2503/277.0      12
 6     7    RR     14    5     8    1  -0.449  2153/257.0  2192/248.2      11
 7     8   RCB     14    5     8    1  -0.607  2146/258.4  2266/254.3      11,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1   SRH     14    9     5    0   0.284  2230/273.3  2193/278.4      18
 1     2   CSK     14    9     5    0   0.253  2488/275.3  2433/277.1      18
 2     3   KKR     14    8     6    0  -0.070  2363/265.1  2425/270.0      16
 3     4    RR     14    7     7    0  -0.250  2130/255.3  2141/249.2      14
 4     5    MI     14    6     8    0   0.317  2380/278.4  2282/277.3      12
 5     6   RCB     14    6     8    0   0.129  2322/264.4  2383/275.4      12
 6     7  PBKS     14    6     8    0  -0.502  2210/268.4  2259/258.5      12
 7     8    DC     14    5     9    0  -0.222  2297/258.0  2304/252.3      10,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    MI     14   10     4    0   0.784  2407/272.1  2242/278.1      20
 1     2   RPS     14    9     5    0   0.176  2180/271.0  2165/275.1      18
 2     3   SRH     14    8     5    1   0.599  2221/252.0  2118/257.5      17
 3     4   KKR     14    8     6    0   0.641  2329/260.5  2300/277.3      16
 4     5  PBKS     14    7     7    0  -0.009  2207/261.2  2229/263.4      14
 5     6    DC     14    6     8    0  -0.512  2219/276.2  2255/264.0      12
 6     7    GL     14    4    10    0  -0.412  2406/269.5  2472/265.0       8
 7     8   RCB     14    3    10    1  -1.299  1845/260.0  2033/242.1       7,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    GL     14    9     5    0  -0.374  2130/264.3  2285/271.1      18
 1     2   RCB     14    8     6    0   0.932  2613/270.2  2345/268.3      16
 2     3   SRH     14    8     6    0   0.245  2082/259.5  2078/267.3      16
 3     4   KKR     14    8     6    0   0.106  2123/253.2  2121/256.2      16
 4     5    MI     14    7     7    0  -0.146  2194/272.2  2190/267.0      14
 5     6    DC     14    7     7    0  -0.155  2040/259.1  2107/262.3      14
 6     7   RPS     14    5     9    0   0.015  2025/244.5  1991/241.1      10
 7     8  PBKS     14    4    10    0  -0.646  2134/269.4  2224/259.5       8,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1   CSK     14    9     5    0   0.709  2262/273.3  2073/274.1      18
 1     2    MI     14    8     6    0  -0.043  2345/272.4  2371/274.2      16
 2     3   RCB     14    7     5    2   1.037  1790/191.1  1693/203.2      16
 3     4    RR     14    7     5    2   0.062  2028/237.3  2002/236.1      16
 4     5   KKR     14    7     6    1   0.253  2044/236.1  2022/240.4      15
 5     6   SRH     14    7     7    0  -0.239  2096/255.2  2126/251.4      14
 6     7    DC     14    5     8    1  -0.049  1981/250.2  1976/248.1      11
 7     8  PBKS     14    3    11    0  -1.436  2003/270.0  2286/258.1       6,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1  PBKS     14   11     3    0   0.968  2427/268.3  2229/276.1      22
 1     2   KKR     14    9     5    0   0.418  2125/264.0  2110/276.3      18
 2     3   CSK     14    9     5    0   0.385  2272/272.0  2178/273.2      18
 3     4    MI     14    7     7    0   0.095  2180/271.3  2170/273.3      14
 4     5    RR     14    7     7    0   0.060  2155/269.5  2164/273.0      14
 5     6   SRH     14    6     8    0  -0.399  2102/263.4  2136/255.1      12
 6     7   RCB     14    5     9    0  -0.428  2093/273.5  2163/268.0      10
 7     8    DC     14    2    12    0  -1.182  1980/263.2  2184/251.0       4,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1   CSK     16   11     5    0   0.530  2461/303.5  2310/305.1      22
 1     2    MI     16   11     5    0   0.441  2514/318.1  2350/315.0      22
 2     3    RR     16   10     6    0   0.322  2405/310.5  2326/313.4      20
 3     4   SRH     16   10     6    0   0.003  2166/308.5  2206/314.4      20
 4     5   RCB     16    9     7    0   0.457  2571/301.0  2451/303.1      18
 5     6  PBKS     16    8     8    0   0.226  2428/305.2  2417/312.5      16
 6     7   KKR     16    6    10    0  -0.095  2290/313.4  2316/313.1      12
 7     8   PWI     16    4    12    0  -1.006  2262/318.4  2519/310.5       8
 8     9    DC     16    3    13    0  -0.848  2234/314.5  2436/306.4       6,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    DC     16   11     5    0   0.617  2365/283.5  2361/306.0      22
 1     2   KKR     16   10     5    1   0.561  2150/285.1  2032/291.1      21
 2     3    MI     16   10     6    0  -0.100  2313/312.3  2343/312.2      20
 3     4   CSK     16    8     7    1   0.100  2232/293.3  2144/285.4      17
 4     5   RCB     16    8     7    1  -0.022  2472/296.2  2505/299.3      17
 5     6  PBKS     16    8     8    0  -0.216  2390/313.3  2455/313.1      16
 6     7    RR     16    7     9    0   0.201  2516/316.0  2402/309.3      14
 7     8   DCH     16    4    11    1  -0.509  2312/298.4  2405/291.3       9
 8     9   PWI     16    4    12    0  -0.551  2321/319.2  2424/310.0       8,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1   RCB     14    9     4    1   0.326  1962/237.0  2000/251.3      19
 1     2   CSK     14    9     5    0   0.443  2118/265.1  1978/262.1      18
 2     3    MI     14    9     5    0   0.040  1998/275.2  1951/270.2      18
 3     4   KKR     14    8     6    0   0.433  1888/249.2  1861/260.4      16
 4     5  PBKS     14    7     7    0  -0.051  2224/275.4  2173/267.4      14
 5     6    RR     14    6     7    1  -0.691  1687/242.2  1801/235.2      13
 6     7   DCH     14    6     8    0   0.222  2140/279.2  2037/273.5      12
 7     8   KTK     14    6     8    0  -0.214  1901/256.2  1989/260.4      12
 8     9   PWI     14    4     9    1  -0.134  1775/247.3  1858/254.2       9
 9    10    DC     14    4     9    1  -0.448  2031/258.2  2076/249.5       9,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    MI     14   10     4    0   1.084  2408/277.0  2100/276.0      20
 1     2   DCH     14    8     6    0  -0.297  2188/277.4  2254/275.4      16
 2     3   CSK     14    7     7    0   0.274  2285/271.1  2257/276.5      14
 3     4   RCB     14    7     7    0   0.219  2166/260.4  2245/277.3      14
 4     5    DC     14    7     7    0   0.021  2155/275.4  2166/277.5      14
 5     6   KKR     14    7     7    0  -0.341  2144/273.0  2192/267.3      14
 6     7    RR     14    6     8    0  -0.514  2179/270.4  2224/259.4      12
 7     8  PBKS     14    4    10    0  -0.478  2278/276.2  2365/271.1       8,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    DC     14   10     4    0   0.311  1978/255.2  1953/262.4      20
 1     2   CSK     14    8     5    1   0.951  2086/255.3  1855/257.1      17
 2     3   RCB     14    8     6    0  -0.191  1994/276.0  2027/273.2      16
 3     4   DCH     14    7     7    0   0.203  2111/272.4  2097/278.1      14
 4     5  PBKS     14    7     7    0  -0.483  1787/251.2  1887/248.3      14
 5     6    RR     14    6     7    1  -0.352  1688/253.1  1810/257.5      13
 6     7    MI     14    5     8    1   0.297  1897/256.2  1802/253.4      11
 7     8   KKR     14    3    10    1  -0.789  1757/248.5  1867/237.5       7,
    Rank  Team  Match  Won  Lost  N/R  Net RR         For     Against  Points
 0     1    RR     14   11     3    0   0.632  2245/261.1  2153/270.2      22
 1     2  PBKS     14   10     4    0   0.509  2352/259.5  2271/265.5      20
 2     3   CSK     14    8     6    0  -0.192  2241/264.2  2195/253.1      16
 3     4    DC     14    7     6    1   0.342  2001/233.2  2031/246.4      15
 4     5    MI     14    7     7    0   0.570  2080/249.1  2096/269.3      14
 5     6   KKR     14    6     7    1  -0.147  1845/242.4  1718/221.4      13
 6     7   RCB     14    4    10    0  -1.160  1983/272.4  2205/261.3       8
 7     8   DCH     14    2    12    0  -0.467  2229/270.0  2307/264.3       4]

In [6]:
url = "https://www.fdic.gov/bank/individual/failed/banklist.html"
df = pd.read_html(url)

In [7]:
df

[                                            Bank Name                City  \
 0                   Metropolitan Capital Bank & Trust             Chicago
 1                        The Santa Anna National Bank          Santa Anna
 2                                Pulaski Savings Bank             Chicago
 3                  The First National Bank of Lindsay             Lindsay
 4               Republic First Bank dba Republic Bank        Philadelphia
 5                                       Citizens Bank            Sac City
 6                            Heartland Tri-State Bank             Elkhart
 7                                 First Republic Bank       San Francisco
 8                                      Signature Bank            New York
 9                                 Silicon Valley Bank         Santa Clara
 10                                  Almena State Bank              Almena
 11                         First City Bank of Florida   Fort Walton Beach
 12                               The First State Bank       Barboursville
 13                                 Ericson State Bank             Ericson
 14                   City National Bank of New Jersey              Newark
 15                                      Resolute Bank              Maumee
 16                              Louisa Community Bank              Louisa
 17                               The Enloe State Bank              Cooper
 18                Washington Federal Bank for Savings             Chicago
 19    The Farmers and Merchants State Bank of Argonia             Argonia
 20                                Fayette County Bank          Saint Elmo
 21  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 22                                     First NBC Bank         New Orleans
 23                                      Proficio Bank  Cottonwood Heights
 24                      Seaway Bank and Trust Company             Chicago

             State   Cert                Acquiring Institution  \
 0        Illinois  57488              First Independence Bank
 1           Texas   5520            Coleman County State Bank
 2        Illinois  28611                      Millennium Bank
 3        Oklahoma   4134               First Bank & Trust Co.
 4    Pennsylvania  27332    Fulton Bank, National Association
 5            Iowa   8758            Iowa Trust & Savings Bank
 6          Kansas  25851               Dream First Bank, N.A.
 7      California  59017            JPMorgan Chase Bank, N.A.
 8        New York  57053                  Flagstar Bank, N.A.
 9      California  24735  First–Citizens Bank & Trust Company
 10         Kansas  15426                          Equity Bank
 11        Florida  16748            United Fidelity Bank, fsb
 12  West Virginia  14361                       MVB Bank, Inc.
 13       Nebraska  18265           Farmers and Merchants Bank
 14     New Jersey  21111                      Industrial Bank
 15           Ohio  58317                   Buckeye State Bank
 16       Kentucky  58112    Kentucky Farmers Bank Corporation
 17          Texas  10716                   Legend Bank, N. A.
 18       Illinois  30570                   Royal Savings Bank
 19         Kansas  17719                          Conway Bank
 20       Illinois   1802            United Fidelity Bank, fsb
 21      Wisconsin  30003  First-Citizens Bank & Trust Company
 22      Louisiana  58302                         Whitney Bank
 23           Utah  35495                    Cache Valley Bank
 24       Illinois  19328                  State Bank of Texas

          Closing Date  Fund  Sort ascending
 0    January 30, 2026                 10550
 1       June 27, 2025                 10549
 2    January 17, 2025                 10548
 3    October 18, 2024                 10547
 4      April 26, 2024                 10546
 5    November 3, 2023                 10545
 6       July 28, 2023                 10544
 7         May 1, 2023                 10543
 8      March 12, 2023                 10540
 9      March 10, 2023                 10539
 10   October 23, 2020                 10538
 11   October 16, 2020                 10537
 12      April 3, 2020                 10536
 13  February 14, 2020                 10535
 14   November 1, 2019                 10534
 15   October 25, 2019                 10533
 16   October 25, 2019                 10532
 17       May 31, 2019                 10531
 18  December 15, 2017                 10530
 19   October 13, 2017                 10529
 20       May 26, 2017                 10528
 21        May 5, 2017                 10527
 22     April 28, 2017                 10526
 23      March 3, 2017                 10525
 24   January 27, 2017                 10524  ]

In [11]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [10]:
df_excel = pd.read_excel("read_data.xlsx")

In [11]:
df_excel.to_pickle("data.pkl")

In [12]:
pd.read_pickle("data.pkl")

Empty DataFrame
Columns: []
Index: []